# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/design_1_axi_smc_4.xci
# IP: The module: 'design_1_axi_smc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/bd_6cc2.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_0/bd_6cc2_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_13/bd_6cc2_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_14/bd_6cc2_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_15/bd_6cc2_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_16/bd_6cc2_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_17/bd_6cc2_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_18/bd_6cc2_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_19/bd_6cc2_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_20/bd_6cc2_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_21/bd_6cc2_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_22/bd_6cc2_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_23/bd_6cc2_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_24/bd_6cc2_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_25/bd_6cc2_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_26/bd_6cc2_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_arsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_rsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_awsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_wsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_bsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_sarn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_srn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_16/bd_6cc2_s01a2s_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_17/bd_6cc2_sawn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_18/bd_6cc2_swn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_19/bd_6cc2_sbn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_20/bd_6cc2_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_21/bd_6cc2_m00arn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_22/bd_6cc2_m00rn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_23/bd_6cc2_m00awn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_24/bd_6cc2_m00wn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_25/bd_6cc2_m00bn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/design_1_axi_smc_4.xci
# IP: The module: 'design_1_axi_smc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/bd_6cc2.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_0/bd_6cc2_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_13/bd_6cc2_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_14/bd_6cc2_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_15/bd_6cc2_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_16/bd_6cc2_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_17/bd_6cc2_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_18/bd_6cc2_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_19/bd_6cc2_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_20/bd_6cc2_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_21/bd_6cc2_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_22/bd_6cc2_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_23/bd_6cc2_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_24/bd_6cc2_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_25/bd_6cc2_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_26/bd_6cc2_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_arsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_rsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_awsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_wsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_bsw_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_s00a2s_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_sarn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_srn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_16/bd_6cc2_s01a2s_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_17/bd_6cc2_sawn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_18/bd_6cc2_swn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_19/bd_6cc2_sbn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_20/bd_6cc2_m00s2a_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_21/bd_6cc2_m00arn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_22/bd_6cc2_m00rn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_23/bd_6cc2_m00awn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_24/bd_6cc2_m00wn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_25/bd_6cc2_m00bn_0_ooc.xdc

# XDC: /home/ubuntu/SOC_Design/course-lab_2/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_axi_smc_4/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
